### ISSUE TITLE
I uninstalled the pack and It left floating command blocks HELP

### ISSUE THREAD

**Issue by OnLeeno** [Hexuar/Norse-Adventure#12]
![Screenshot_6](https://github.com/Hexuar/Norse-Adventure/assets/149537533/9a8a4653-ecd9-478e-845b-f0ea7e2b7c52)
I used this datapack for a day and decided I didn't want to use it anymore because I travel more often by land, I decided to uninstall and when I did It left this floating command block floating in the water, I wan walk through it, and it has nothing inside, it had some pigs and boats and more stuff that I managed to get rid of but it won't go away.

HELP

**Comment by Hexuar** [comment]
Run `/function norse_adventure:uninstall` before uninstalling to remove any remaining entities
