### ISSUE TITLE
Transparent boat

### ISSUE THREAD

**Issue by SpoGik** [Hexuar/Norse-Adventure#13]
Everything is working well on my server. There is only one problem, the boat is transparent, you can't walk on it. I also noticed that chairs can be "killed", But this is how I understood the convention. Can you fix the transparency in a future update? It's just that in the video you're walking on a boat.

I am writing through a translator, sorry for the inaccuracies.

**Comment by Hexuar** [comment]
Hey there! Sorry for the late response. Since a recent update floor collision is disabled by default, since it can cause issues on lower end servers. To enable it, run `/scoreboard players set #floor_collision norse_adventure.value 1 `
