### ISSUE TITLE
Incompatible with 1.20.1

### ISSUE THREAD

**Issue by Inkycat7167** [Hexuar/Norse-Adventure#2]
Excuse me but this datapack doesn't seem to work with 1.20.1 , May i ask if you have any plans to update to that version?

**Comment by Hexuar** [comment]
A lot of the datapack's features build on the new datapack features introduced in 1.20.2 and while it would be possible to port it to earlier versions, It would be more effort than it's worth to me.

**Comment by Inkycat7167** [comment]
i see, so basically i'm screwed if i wanted it to work in 1.20.1 , i appreciate the help.
