### ISSUE TITLE
Advancements bug

### ISSUE THREAD

**Issue by aercanist** [Hexuar/Norse-Adventure#7]
The tutorial advancements descriptions don't work
MC 1.20.2, same on 1.20.4 with the newest pack
![1](https://github.com/Hexuar/Norse-Adventure/assets/77434498/49510772-00ad-446e-a6d7-6fe96f22e755)

**Comment by Hexuar** [comment]
You need to install the resourcepack for the textures to work. Which can be a tad difficult on modrinth unfortunately.

Select the newest version, do not click the download button directly. This will bring you to the version page, containing the downloads for both the data- and resourcepack.
